### ISSUE TITLE
Flow control

### ISSUE THREAD

**Issue by GhostNr1** [CorpWar/CorpNet#3]
There would be good if there was some kind of flow control so that you don't flood the connection. 
If the ping goes up unreliable packages can be thrown away and not every package will be sent.
If reliable packages we can put a small delay between every send to that connection.
If the ping time goes down we can try to send faster.
We also need some kind of package loss statistics to figure out if we need to raise or lower the speed of the connection.

**Comment by CorpWar** [comment]
This issue have been implemented. There should be a stable flow control now.
