### ISSUE TITLE
Rewrite the framework

### ISSUE THREAD

**Issue by CorpWar** [CorpWar/CorpNet#7]
There are a lot of duplicate code in server and client. 
Rewrite it in a way so it will be easier to do client<->server and also peer<->peer connection.

**Comment by shock2provide** [comment]
Just out of curiosity, could you give an ETA for 2.0.0?
I discovered your work today and I'm tempted to use it in my project but would like to know how active you are currently working on it.

Thanks either way for the work you have already put into this project.

**Comment by CorpWar** [comment]
Sorry for the late answer. I didn't think anyone was looking at this library and have been slow to read mail on this account. If you should use it then download the latest source 1.6.0. There are a severe race condition in 1.5.0 when you use split messages. I had it fixed but forget to check in the fix.

And now for your question, I have had this on a back burner. I use it in one of my game to try it out so it work in a real situation.
If I remember correct when I was looking at the code I think the client<->server code was kinda good, need some more commenting. It just felt to be a lot of duplicate code. But I need to do a peer<->peer connection. So that will be for 2.0.0. So if client<->server is good enough I think this should do for now.
If you have any suggestion to improvement just put a comment in this issue and I should take a look at it.
